# Seperating config per file
AuctionsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    # To make it dynamic and per environment with ease
    TableName: AuctionsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH